spring:
  profiles:
    active: "local"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---

spring:
  config:
    activate:
      on-profile: "prod"

---

spring:
  config:
    activate:
      on-profile: "dev"

---

spring:
  config:
    activate:
      on-profile: "local"
